### ISSUE TITLE
Center star selection area

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-app#286]
- In the Challenge Header
- In the Challenge Card

**Comment by rrchai** [comment]
to vertically align `mat-icon-button` with title in the `mat-card-header`:

```html
<mat-card>
  <mat-card-header>
    <mat-card-title>This is title</mat-card-title>
    <button mat-icon-button>
      <mat-icon inline=true>home</mat-icon>
    </button>
  </mat-card-header>
  <mat-card-content>
  </mat-card-content>
<mat-card>
```
```css
.mat-card-header {
  display: inline-flex;
  align-items: center;
}

.mat-card-title {
  margin: 0;
  font-size: 14px;
}

.mat-card-button {
  line-height: unset;
  font-size: 14px;
}
```
related to the issue [Icons inside mat-icon-button not vertically centered](https://github.com/angular/components/issues/8842#issuecomment-595439699) on angular
